# Generated by Django 4.0.2 on 2022-02-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.01)),
                ('availability', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
