# Generated by Django 4.0.2 on 2022-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hash_summ',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
