# Generated by Django 4.0.2 on 2022-02-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_hash_summ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
    ]
